name: Motion YYC
favicon: null
layout_spectrum: 0.2444
typography_spectrum: 0.369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6005776266101748
  lightness: 0.0625
  saturation: 0.8915127799846232
  rhythmicContrast: 0.050403077621012926
purpose: []
